function valueLabel = addMetricLabel(parent, labelText)
    uilabel(parent, 'Text', labelText);
    valueLabel = uilabel(parent, ...
        'Text', '-', ...
        'HorizontalAlignment', 'right', ...
        'FontWeight', 'bold');
end
