function field = addNumericField(parent, labelText, value, lower, upper, callback)
    uilabel(parent, 'Text', labelText);
    field = uieditfield(parent, 'numeric', ...
        'Value', value, ...
        'Limits', [lower upper], ...
        'RoundFractionalValues', 'off', ...
        'ValueChangedFcn', @(~, ~) callback());
end
