function data = germanTransferTaxRates()
    data = { ...
        'Baden-Wuerttemberg', 5.0; ...
        'Bavaria', 3.5; ...
        'Berlin', 6.0; ...
        'Brandenburg', 6.5; ...
        'Bremen', 5.0; ...
        'Hamburg', 5.5; ...
        'Hesse', 6.0; ...
        'Lower Saxony', 5.0; ...
        'Mecklenburg-Western Pomerania', 6.0; ...
        'North Rhine-Westphalia', 6.5; ...
        'Rhineland-Palatinate', 5.0; ...
        'Saarland', 6.5; ...
        'Saxony', 5.5; ...
        'Saxony-Anhalt', 5.0; ...
        'Schleswig-Holstein', 6.5; ...
        'Thuringia', 5.0 ...
    };
end
