function in = readReverseInputs(app)
    in.mode = app.Reverse.mode.Value;
    in.monthlyRent = app.Reverse.monthlyRent.Value;
    in.targetReturnPct = app.Reverse.targetReturnPct.Value;
    in.downPaymentPct = app.Reverse.downPaymentPct.Value;
    in.interestRate = app.Reverse.interestRate.Value;
    in.loanTermYears = app.Reverse.loanTermYears.Value;
    in.auxCostPct = app.Reverse.auxCostPct.Value;
    in.includeAgent = app.Reverse.includeAgent.Value;
    in.closingCosts = app.Reverse.closingCosts.Value;
    in.renovationCosts = app.Reverse.renovationCosts.Value;
    in.propertyTax = app.Reverse.propertyTax.Value;
    in.insurance = app.Reverse.insurance.Value;
    in.hoa = app.Reverse.hoa.Value;
    in.utilities = app.Reverse.utilities.Value;
    in.vacancyPct = app.Reverse.vacancyPct.Value;
    in.maintenancePct = app.Reverse.maintenancePct.Value;
    in.capexPct = app.Reverse.capexPct.Value;
    in.managementPct = app.Reverse.managementPct.Value;
    in.otherIncome = 0;
    in.rentGrowthPct = 0;
    in.expenseInflationPct = 0;
    in.appreciationPct = 0;
    in.horizonYears = 30;
end
