function in = readForwardInputs(app)
    in.purchasePrice = app.Forward.purchasePrice.Value;
    in.monthlyRent = app.Forward.monthlyRent.Value;
    in.otherIncome = app.Forward.otherIncome.Value;
    in.downPaymentPct = app.Forward.downPaymentPct.Value;
    in.interestRate = app.Forward.interestRate.Value;
    in.loanTermYears = app.Forward.loanTermYears.Value;
    in.auxCostPct = app.Forward.auxCostPct.Value;
    in.includeAgent = app.Forward.includeAgent.Value;
    in.closingCosts = app.Forward.closingCosts.Value;
    in.renovationCosts = app.Forward.renovationCosts.Value;
    in.propertyTax = app.Forward.propertyTax.Value;
    in.insurance = app.Forward.insurance.Value;
    in.hoa = app.Forward.hoa.Value;
    in.utilities = app.Forward.utilities.Value;
    in.vacancyPct = app.Forward.vacancyPct.Value;
    in.maintenancePct = app.Forward.maintenancePct.Value;
    in.capexPct = app.Forward.capexPct.Value;
    in.managementPct = app.Forward.managementPct.Value;
    in.rentGrowthPct = app.Forward.rentGrowthPct.Value;
    in.expenseInflationPct = app.Forward.expenseInflationPct.Value;
    in.appreciationPct = app.Forward.appreciationPct.Value;
    in.horizonYears = round(app.Forward.horizonYears.Value);
end
