function in = readForwardInputs(app)
    in.purchasePrice = app.Forward.purchasePrice.Value;
    in.monthlyRent = app.Forward.monthlyRent.Value;
    in.downPaymentPct = app.Forward.downPaymentPct.Value;
    in.interestRate = app.Forward.interestRate.Value;
    in.financingMode = app.Forward.financingMode.Value;
    in.loanTermYears = app.Forward.loanTermYears.Value;
    in.initialPrincipalPct = app.Forward.initialPrincipalPct.Value;
    in.minimumPrincipalPct = app.Forward.minimumPrincipalPct.Value;
    in.transferTaxPct = app.Forward.transferTaxPct.Value;
    in.notaryPct = app.Forward.notaryPct.Value;
    in.landRegistryPct = app.Forward.landRegistryPct.Value;
    in.includeAgent = app.Forward.includeAgent.Value;
    in.renovationCosts = app.Forward.renovationCosts.Value;
    in.hoaContribution = app.Forward.hoaContribution.Value;
    in.hoaTransferablePct = app.Forward.hoaTransferablePct.Field.Value;
    in.annualMaintenanceCosts = app.Forward.annualMaintenanceCosts.Value;
    in.buildingSharePct = app.Forward.buildingSharePct.Value;
    in.buildingCompletionYear = round(app.Forward.buildingCompletionYear.Value);
    in.marginalTaxRatePct = app.Forward.marginalTaxRatePct.Value;
    in.vacancyPct = app.Forward.vacancyPct.Value;
    in.rentGrowthPct = app.Forward.rentGrowthPct.Value;
    in.expenseInflationPct = app.Forward.expenseInflationPct.Value;
    in.appreciationPct = app.Forward.appreciationPct.Value;
    in.horizonYears = round(app.Forward.horizonYears.Value);
end
