function in = readReverseInputs(app)
    in.mode = app.Reverse.mode.Value;
    in.monthlyRent = app.Reverse.monthlyRent.Value;
    in.targetReturnPct = app.Reverse.targetReturnPct.Value;
    in.downPaymentPct = app.Reverse.downPaymentPct.Value;
    in.interestRate = app.Reverse.interestRate.Value;
    in.loanTermYears = app.Reverse.loanTermYears.Value;
    in.transferTaxPct = app.Reverse.transferTaxPct.Value;
    in.notaryPct = app.Reverse.notaryPct.Value;
    in.landRegistryPct = app.Reverse.landRegistryPct.Value;
    in.includeAgent = app.Reverse.includeAgent.Value;
    in.renovationCosts = app.Reverse.renovationCosts.Value;
    in.hoaContribution = app.Reverse.hoaContribution.Value;
    in.hoaTransferablePct = app.Reverse.hoaTransferablePct.Field.Value;
    in.annualMaintenanceCosts = app.Reverse.annualMaintenanceCosts.Value;
    in.buildingSharePct = app.Reverse.buildingSharePct.Value;
    in.buildingCompletionYear = round(app.Reverse.buildingCompletionYear.Value);
    in.marginalTaxRatePct = app.Reverse.marginalTaxRatePct.Value;
    in.vacancyPct = app.Reverse.vacancyPct.Value;
    in.rentGrowthPct = 0;
    in.expenseInflationPct = 0;
    in.appreciationPct = 0;
    in.horizonYears = 30;
end
